---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: bundle config packagecloud.io $PACKAGECLOUD_READ_TOKEN
      - run: bundle install
      - run: bundle exec rake test
      # Clean up any .gem files from all previous builds
      - run: rm -f *.gem
      - run: gem install package_cloud
      - run: gem build $(ls *.gemspec)
      - run: package_cloud push avvo/gems $(ls *.gem)
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
